// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX7TTkyRTSb6hJ910C3XHrAIxY4EHP2bo',
    appId: '1:400649966615:web:8a27e3d12b2dfe656e3852',
    messagingSenderId: '400649966615',
    projectId: 'lost-found-1771621310',
    authDomain: 'lost-found-1771621310.firebaseapp.com',
    storageBucket: 'lost-found-1771621310.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfE5ht7uZ09wnlaeFJTKu1woutlkdd-iw',
    appId: '1:400649966615:android:81f34330bc019d3d6e3852',
    messagingSenderId: '400649966615',
    projectId: 'lost-found-1771621310',
    storageBucket: 'lost-found-1771621310.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZBJTHKdzhMwfOIAHQT0x-bwPT3wit_I',
    appId: '1:400649966615:ios:c830300a1311863a6e3852',
    messagingSenderId: '400649966615',
    projectId: 'lost-found-1771621310',
    storageBucket: 'lost-found-1771621310.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaZBJTHKdzhMwfOIAHQT0x-bwPT3wit_I',
    appId: '1:400649966615:ios:c830300a1311863a6e3852',
    messagingSenderId: '400649966615',
    projectId: 'lost-found-1771621310',
    storageBucket: 'lost-found-1771621310.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX7TTkyRTSb6hJ910C3XHrAIxY4EHP2bo',
    appId: '1:400649966615:web:4e6a2f73423d1fed6e3852',
    messagingSenderId: '400649966615',
    projectId: 'lost-found-1771621310',
    authDomain: 'lost-found-1771621310.firebaseapp.com',
    storageBucket: 'lost-found-1771621310.firebasestorage.app',
  );
}
